Создана структура файлов проекта
AlexanderKorobchenko/team_project_html_css pull request #2
Opened 2021-04-21 21:57 UTC by AlexanderKorobchenko

2021-04-21 22:01 UTC, AlexanderKorobchenko reviewed
Всё ок

2021-04-21 22:03 UTC, AlexanderKorobchenko commented
> Всё ок

2021-04-22 09:14 UTC, Olena-Kandibula requested changes

2021-04-22 09:14 UTC, Olena-Kandibula commented on src/index.html
> +<html lang="en">
title можно красивый написать

2021-04-22 16:22 UTC, AlexanderKorobchenko commented on src/index.html
> +<html lang="en">
Странно, я вроде тоже менял на инглишь)

2021-04-22 17:50 UTC, closed without merging